ENH: Add LICENSE file
Add LICENSE file.

Add the corresponding badge to the `README` file.

Bump `setuptools` to avoid configuration errors:
```
ValueError: invalid pyproj
configuration error: `proj

  - keys:
      'file': {type: str
    required: ['file']
  - keys:
      'text': {type: str
    required: ['text']

[end of output]
```

raised for example at:
https://github.com/SlicerDMRI/dmriseg/actions/runs/20623415773/job/59229682936?pr=147#step:5:171